name: device_edg
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.0
  tflite_flutter: ^0.11.0
  http: ^0.13.0
  path_provider: ^2.0.0
  geolocator: ^11.0.0
  image: ^4.2.0
  background_fetch: ^1.2.3
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  flutter_local_notifications: ^17.0.0
  battery_plus: ^5.0.3
  flutter_launcher_icons: "^0.13.1"
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1

flutter:

  uses-material-design: true
  assets: 
  - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # <--- Onde você vai salvar o arquivo de ícone
  min_sdk_android: 21 # ou a versão mínima do Android do seu projeto

flutter_native_splash:
  # Cor de fundo da tela de splash
  color: "#FFFFFF" 
  # Caminho para sua imagem (logo) que será exibida
  image: "assets/splash_logo.png" 
  
  # Opcional: Configurações específicas para Android e iOS
  android_gravity: center
  ios_content_mode: center
